
###

GET http://localhost:3000/user/setupDB

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username" : "mahi",
    "password" : "mahi"
}

###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username" : "test",
    "password" : "test",
    "email" : "test@gmail.com",
    "mobileNo" : 9889812345
}